### ISSUE TITLE
Pressing 'Enter' on a textarea with regex types the word 'Enter'

### ISSUE THREAD

**Issue by MattPurland** [RobinHerbots/jquery.inputmask#2742]
- Describe the bug
Pressing the return or enter key in a textarea with regex types the word 'Enter'

- Add a link to a codepen, jsfiddle or other example page which shows the problem
https://codepen.io/MattPurland/pen/yLGEOoj

- OS:
Windows 10

- Browser
Chrome

- Inputmask version
5.0.8

**Comment by MattPurland** [comment]
I've figured out a workaround using the onKeyDown event:

```
        onKeyDown: (e) => {
            if(e.which == 13) {
                e.target.value = e.target.value + "\r";
                return false;
            }
        }
```

**Comment by RobinHerbots** [comment]
Hi @MattPurland,

This is already fixed in the 5.0.9-beta version.

**Comment by MattPurland** [comment]
I've just installed the latest beta and it looks like it's still typing 'Enter', am I missing something? The only option I'm setting is:

```
regex: `[a-zA-Z0-9 \r\n!"£$%^&*()_+-='#@~¬<>\?]*`
```

**Comment by MattPurland** [comment]
Checked and working perfectly, thanks

**Comment by MattPurland** [comment]
Sorry, it looks like this still isn't working (I'm testing with 5.0.9-beta.32). Please see updated codepen

**Comment by MattPurland** [comment]
Updated workaround for those interested

```
            if(e.which == 13) {
                let value = e.target.value,
                    index = e.target.selectionStart;

                e.target.value = value.slice(0, index) + "\r" + value.slice(index);
                e.target.setSelectionRange(index + 1, index + 1);
                
                return false;
            }
```

**Comment by RobinHerbots** [comment]
@MattPurland ,

Version 5.0.10-beta.33 should work.
